"""empty message

Revision ID: 1e6d4c91c68b
Revises: 884a19195474
Create Date: 2022-11-23 08:21:55.864449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e6d4c91c68b'
down_revision = '884a19195474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedor')
    op.drop_table('ventas')
    op.drop_table('producto')
    op.drop_table('usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('idUsuario', sa.INTEGER(), server_default=sa.text('nextval(\'"usuarios_idUsuario_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nombreUsuario', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('correo', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('edad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('idUsuario', name='usuarios_pkey'),
    sa.UniqueConstraint('correo', name='usuarios_correo_key')
    )
    op.create_table('producto',
    sa.Column('idProducto', sa.INTEGER(), server_default=sa.text('nextval(\'"producto_idProducto_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nombreProducto', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('desProducto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idProducto', name='producto_pkey')
    )
    op.create_table('ventas',
    sa.Column('idVenta', sa.INTEGER(), server_default=sa.text('nextval(\'"ventas_idVenta_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idVenta', name='ventas_pkey')
    )
    op.create_table('proveedor',
    sa.Column('idProveedor', sa.INTEGER(), server_default=sa.text('nextval(\'"proveedor_idProveedor_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nombreProveedor', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idProveedor', name='proveedor_pkey')
    )
    # ### end Alembic commands ###
